# Generated by Django 5.1.6 on 2025-03-23 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
