# Generated by Django 5.1.6 on 2025-03-23 22:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("company", "0002_alter_company_website"),
    ]

    operations = [
        migrations.AlterField(
            model_name="companyoffice",
            name="company",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="offices",
                to="company.company",
            ),
        ),
    ]
