# Generated by Django 5.1.6 on 2025-04-19 15:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_alter_companyoffice_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companymanager',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='managers', to='company.company'),
        ),
    ]
