# Generated by Django 5.1.6 on 2025-04-20 17:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("job", "0004_jobapplication_is_cover_letter_ai_generated"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobapplication",
            name="is_cover_letter_ai_report",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
